INSERT INTO recipes (name, description, image_url)
VALUES ("Shrimp Scampi", "Quick and tasty shrimp and pasta, finished with lemon and red pepper flakes.", 1),
       ("Buffalo Chicken Enchiladas", "A new take on enchiladas, these spicy, cheesy enchiladas make a great weeknight meal.".00, 5),
       ("Glazed Salmon and Spiced Carrots", "Sweet and tangy salmon with a side of spiced carrots.", 2),
       ("Ravioli with Sage and Walnut Butter", "Spruce up store bought ravioli with savory spices and a walnut butter sauce.".00, 1),
       ("Turkey Pad Thai", "A healthy take on pad thai. Loaded with fresh veggies and finished with a tasty peanut sauce, this is a great week night meal.", 4), 
       ("Garlic Butter Baked Salmon", "Spruce up your salmon with a garlic butter marinade.", 1),
       ("Chipotle Chicken Skewers", "A new take on enchiladas, these spicy, cheesy enchiladas make a great weeknight meal.".00, 5),
       ("Hamburger", 97000.00, 2),
       ("Potato Wedges", 102000.00, 1),
       ("Zuppa Toscana", 72000.00, 4), 
        ("Pasta Salad", "Quick and tasty shrimp and pasta, finished with lemon and red pepper flakes.", 1),
       ("Cool Summer Soba Noodle Salad", "A new take on enchiladas, these spicy, cheesy enchiladas make a great weeknight meal.".00, 5),
       ("Parmesan Bread Twist", 97000.00, 2),
       ("Chipotle Stout Chili", 102000.00, 1);
       



INSERT INTO ingredients (name)
VALUES ("Shrimp"),
       ("Salmon"),
       ("Ground Beef"),
       ("Chicken"),
       ("Egg"),
       ("Salmon"),
       ("Pepperoni"),
       ("Bacon"),
       ("Turkey"),
       ("Sausage"),
       ("Rice"),
       ("Pasta"),
       ("Bread"),
       ("Tortillas"),
       ("Ravioli"),
       ("Soba Noodles"),
       ("Pizza Dough"),
       ("Chipolte Peppers"),
       ("Scallions"),
       ("Carrots"),
       ("Bean Sprouts"),
       ("Onion"),
       ("Potatoes"),
       ("Kale"),
       ("Tomatos"),
        ("Cucumber"),
       ("Chicken Broth"),
       ("Lemon"),
       ("Lime"),
       ("White Wine"),
       ("Mustard"),
       ("Almonds"),
       ("Walnuts"),
       ("Brown Sugar"),
       ("Miso Paste"),
       ("Kidney Beans"),
       ("Stout Beer"),
       ("Heavy Cream"),
       ("Parmesean Cheese"),
       ("Cheddar Cheese"),
       ("Cream Cheese"),
       ("Blue Cheese"),
       ("Mozerella Cheese"), 
       ("Mushrooms"), 
       ("Bread Crumbs"), 
       ("Ranch Mix");
       

