INSERT INTO recipes (name, description, image_url)
VALUES ("Shrimp Scampi", "Quick and tasty shrimp and pasta, finished with lemon and red pepper flakes.", "null"),
       ("Buffalo Chicken Enchiladas", "A new take on enchiladas, these spicy, cheesy enchiladas make a great weeknight meal.", "null"),
       ("Glazed Salmon and Spiced Carrots", "Sweet and tangy salmon with a side of spiced carrots.", "null"),
       ("Ravioli with Sage and Walnut Butter", "Spruce up store bought ravioli with savory spices and a walnut butter sauce.", "null"),
       ("Turkey Pad Thai", "A healthy take on pad thai. Loaded with fresh veggies and finished with a tasty peanut sauce, this is a great week night meal.", "null"), 
       ("Garlic Butter Baked Salmon", "Spruce up your salmon with a garlic butter marinade.", "null"),
       ("Chipotle Chicken Skewers", "A new take on enchiladas, these spicy, cheesy enchiladas make a great weeknight meal.", "null"),
       ("Hamburger", "An American classic. This hamburger recipe gives you a quick and easy take on a classic.", "null"),
       ("Potato Wedges", "Crispy, seasoned potatoes for a vegetarian, one pan meal.", "null"),
       ("Zuppa Toscana", "A rich, classic Italian soup.", "null"), 
        ("Pasta Salad", "A summertime classic, this pasta salad is loaded with veggies and finished with a creamy dressing.", "null"),
       ("Cool Summer Soba Noodle Salad", ".", "null"),
       ("Parmesan Bread Twist", "Short on ingredients, but big on flavor. These pizza joint inpired twists are a crowd favorite", "null"),
       ("Chipotle Stout Chili", "A hearty, wintertime meal, this chili is loaded with meat and veggies and is sure to please everyone.", "null"), 
       ("Chicken Marsala", "Roasted chicken in a creamy marsala sauce. This is the perfect chilly night weeknight meal.", "null"),
       ("Chili Glazed Salmon", "Sweet and spicy salmon in a flavorful glaze.", "null"),
       ("Baked Ranch Chicken", "Baked chicken coated in ranch seasoning and bread crumbs for a flavorful, crispy dinner.", "null"),
       ("Baked Shrimp", "Simple and flavorful, these baked shrimp are easy to prep, but full of flavor.", "null"), 
       ("Cheeseburger Stuffed Bell Pepper", "description", "null" ),
       ("Baked Mac & Cheese", "A grown up version of a childhood classic, this cheesy pasta is finished in the oven for a crispy upgrade.", "null");
       



INSERT INTO ingredients (name)
VALUES ("Shrimp"),
       ("Salmon"),
       ("Ground Beef"),
       ("Chicken"),
       ("Egg"),
       ("Salmon"),
       ("Pepperoni"),
       ("Bacon"),
       ("Turkey"),
       ("Sausage"),
       ("Rice"),
       ("Pasta"),
       ("Bread"),
       ("Tortillas"),
       ("Ravioli"),
       ("Soba Noodles"),
       ("Pizza Dough"),
       ("Chipolte Peppers"),
       ("Scallions"),
       ("Carrots"),
       ("Bean Sprouts"),
       ("Onion"),
       ("Potatoes"),
       ("Kale"),
       ("Tomatos"),
        ("Cucumber"),
       ("Chicken Broth"),
       ("Lemon"),
       ("Lime"),
       ("White Wine"),
       ("Mustard"),
       ("Almonds"),
       ("Walnuts"),
       ("Brown Sugar"),
       ("Miso Paste"),
       ("Kidney Beans"),
       ("Stout Beer"),
       ("Heavy Cream"),
       ("Parmesean Cheese"),
       ("Cheddar Cheese"),
       ("Cream Cheese"),
       ("Blue Cheese"),
       ("Mozerella Cheese"), 
       ("Mushrooms"), 
       ("Bread Crumbs"), 
       ("Ranch Mix"),
       ("Sour Cream");
       


INSERT INTO ingredient_recipe (recipe_id, ingredient_id)
VALUES 
(6, 2),
(6, 28),
(7, 4),
(7, 18),
(8, 3),
(8, 13),
(9, 23),
(20, 12),
(20, 40);
(15, 4),
(15, 44),
(15, 12),
(15, 30),
(15, 27),
(16, 2),
(16, 19),
(17, 4),
(17, 45),
(17, 46),
(17, 47),
(18, 2),
(18, 39),
(19, 3),
(19, 22),
(19, 11),
(19, 40);


